name: Build and Release Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: akashington
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t akashington/workspace:latest \
                       -t akashington/workspace:${{ github.run_number }} .

      - name: Push Docker images
        run: |
          docker push akashington/workspace:latest
          docker push akashington/workspace:${{ github.run_number }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.run_number }}
          name: Release v${{ github.run_number }}
          body: |
            Docker image pushed to Docker Hub.
            - **Image (latest):** `docker pull akashington/workspace:latest`
            - **Image (tagged):** `docker pull akashington/workspace:${{ github.run_number }}`
            - **Commit:** ${{ github.sha }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}